version: '2'

services: 
  mongo:
    image: mongo
    command: mongod --smallfiles
    ports: 
      - "27017:27017"

  web:
    build: .
    ports: 
      - "8090:8090"
    links: 
      - mongo
    environment: 
      - PORT: 8090


