version: '2'

services: 
  mongo:
    image: mongo
    command: mongod --smallfiles
    networks: 
      - joint
    ports: 
      - "27017:27017"

  web:
    build: .
    ports: 
      - "8090:8090"
    links: 
      - mongo
    networks: 
      - joint

  networks: 
    joint: