version: '2'

services: 
  database:
    image: mongo
    command: mongod --smallfiles
    ports: 
      - "27017:27017"

  web:
    build: .
    ports: 
      - "8090:8090"
    links: 
      - database
    environment: 
      - PORT = 8090
      - DB_NAME = database


