version: '2'

services: 
  mongo:
    image: mongo
    command: mongod --smallfiles
    networks: 
      - all 

  web:
    build: .
    ports: 
      - "8090:8090"
    volumes:
      - .:/root
    depends_on: 
      - mongo
    networks:
      - all

networks: 
  all: